// This file is generated by scripts/generate-components-dts.mjs
import "@vue/runtime-core"

declare module "@vue/runtime-core" {
  export interface GlobalComponents {
    XBreadcrumb: typeof import("./components/breadcrumb/index")["default"];
    XButton: typeof import("./components/button/index")["default"];
    XCheckbox: typeof import("./components/checkbox/index")["default"];
    XCheckboxGroup: typeof import("./components/checkbox-group/index")["default"];
    XCollapse: typeof import("./components/collapse/index")["default"];
    XCollapseGroup: typeof import("./components/collapse-group/index")["default"];
    XColorPicker: typeof import("./components/color-picker/index")["default"];
    XDialog: typeof import("./components/dialog/index")["default"];
    XFixed: typeof import("./components/fixed/index")["default"];
    XIcon: typeof import("./components/icon/index")["default"];
    XInformation: typeof import("./components/information/index")["default"];
    XInput: typeof import("./components/input/index")["default"];
    XInputNumber: typeof import("./components/input-number/index")["default"];
    XLink: typeof import("./components/link/index")["default"];
    XLoading: typeof import("./components/loading/index")["default"];
    XMenu: typeof import("./components/menu/index")["default"];
    XMessage: typeof import("./components/message/index")["default"];
    XPopup: typeof import("./components/popup/index")["default"];
    XRadio: typeof import("./components/radio/index")["default"];
    XRadioButton: typeof import("./components/radio-button/index")["default"];
    XRadioButtonGroup: typeof import("./components/radio-button-group/index")["default"];
    XScroll: typeof import("./components/scroll/index")["default"];
    XSelect: typeof import("./components/select/index")["default"];
    XSlider: typeof import("./components/slider/index")["default"];
    XSwitch: typeof import("./components/switch/index")["default"];
    XTabs: typeof import("./components/tabs/index")["default"];
    XTag: typeof import("./components/tag/index")["default"];
    XToast: typeof import("./components/toast/index")["default"];
    XTooltip: typeof import("./components/tooltip/index")["default"];
  }
}
