// This file is generated by scripts/generate-global-dts.mjs
import "@vue/runtime-core"

declare module "@vue/runtime-core" {
  export interface ComponentCustomProperties {
    $dialog: typeof import("./global/dialog/index")["default"];
    $information: typeof import("./global/information/index")["default"];
    $message: typeof import("./global/message/index")["default"];
    $toast: typeof import("./global/toast/index")["default"];
  }
}
