/** This file is automatically generated by the build script */
import { type App } from "vue";
import { XBreadcrumb } from "./components/breadcrumb/index.ts";
import { XButton } from "./components/button/index.ts";
import { XCheckbox } from "./components/checkbox/index.ts";
import { XCheckboxGroup } from "./components/checkbox-group/index.ts";
import { XCollapse } from "./components/collapse/index.ts";
import { XCollapseGroup } from "./components/collapse-group/index.ts";
import { XColorPicker } from "./components/color-picker/index.ts";
import { XDialog } from "./components/dialog/index.ts";
import { XFixed } from "./components/fixed/index.ts";
import { XIcon } from "./components/icon/index.ts";
import { XInformation } from "./components/information/index.ts";
import { XInput } from "./components/input/index.ts";
import { XInputNumber } from "./components/input-number/index.ts";
import { XLink } from "./components/link/index.ts";
import { XLoading } from "./components/loading/index.ts";
import { XMenu } from "./components/menu/index.ts";
import { XMessage } from "./components/message/index.ts";
import { XPopup } from "./components/popup/index.ts";
import { XRadio } from "./components/radio/index.ts";
import { XRadioButton } from "./components/radio-button/index.ts";
import { XRadioButtonGroup } from "./components/radio-button-group/index.ts";
import { XScroll } from "./components/scroll/index.ts";
import { XSelect } from "./components/select/index.ts";
import { XSlider } from "./components/slider/index.ts";
import { XSwitch } from "./components/switch/index.ts";
import { XTabs } from "./components/tabs/index.ts";
import { XTag } from "./components/tag/index.ts";
import { XToast } from "./components/toast/index.ts";
import { XTooltip } from "./components/tooltip/index.ts";


import { vLoading } from "./directives/loading/index.ts";
import { vRipple } from "./directives/ripple/index.ts";


import dialog from "./global/dialog/index.ts";
import information from "./global/information/index.ts";
import message from "./global/message/index.ts";
import toast from "./global/toast/index.ts";

// 导出内部所有内容
export * from "./components/breadcrumb/index.ts";
export * from "./components/button/index.ts";
export * from "./components/checkbox/index.ts";
export * from "./components/checkbox-group/index.ts";
export * from "./components/collapse/index.ts";
export * from "./components/collapse-group/index.ts";
export * from "./components/color-picker/index.ts";
export * from "./components/dialog/index.ts";
export * from "./components/fixed/index.ts";
export * from "./components/icon/index.ts";
export * from "./components/information/index.ts";
export * from "./components/input/index.ts";
export * from "./components/input-number/index.ts";
export * from "./components/link/index.ts";
export * from "./components/loading/index.ts";
export * from "./components/menu/index.ts";
export * from "./components/message/index.ts";
export * from "./components/popup/index.ts";
export * from "./components/radio/index.ts";
export * from "./components/radio-button/index.ts";
export * from "./components/radio-button-group/index.ts";
export * from "./components/scroll/index.ts";
export * from "./components/select/index.ts";
export * from "./components/slider/index.ts";
export * from "./components/switch/index.ts";
export * from "./components/tabs/index.ts";
export * from "./components/tag/index.ts";
export * from "./components/toast/index.ts";
export * from "./components/tooltip/index.ts";

// 导出类型
export type {
  ComponentType,
  ComponentSize,
  ComponentVariant,
  ComponentShape,
  ModelValue,
  Direction,
  VerticalAlign,
  TransitionName
} from "./types/basic";


export { useDialog } from "./global/dialog/index.ts";
export { useInformation } from "./global/information/index.ts";
export { useMessage } from "./global/message/index.ts";
export { useToast } from "./global/toast/index.ts";


const components = [
  XBreadcrumb,
  XButton,
  XCheckbox,
  XCheckboxGroup,
  XCollapse,
  XCollapseGroup,
  XColorPicker,
  XDialog,
  XFixed,
  XIcon,
  XInformation,
  XInput,
  XInputNumber,
  XLink,
  XLoading,
  XMenu,
  XMessage,
  XPopup,
  XRadio,
  XRadioButton,
  XRadioButtonGroup,
  XScroll,
  XSelect,
  XSlider,
  XSwitch,
  XTabs,
  XTag,
  XToast,
  XTooltip
];
const directives = {
  loading: vLoading,
  ripple: vRipple
};
const globals = {
  $dialog: dialog,
  $information: information,
  $message: message,
  $toast: toast
};

export default {
  install: (app: App) => {
    components.forEach(component => {
      app.use(component);
    });

    Object.entries(directives).forEach(([name, directive]) => {
      app.directive(name, directive);
    });

    Object.entries(globals).forEach(([name, global]) => {
      app.config.globalProperties[name] = global;
    });

    app.config.globalProperties.$XUI = {
      version: "0.0.1"
    };
  }
};
