name: 部署文档和 Demo
on:
  push:
    branches: [main]
    paths:
      - 'docs/**'
      - '.github/workflows/gh-pages.yml'

jobs:
  create-gh-pages:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: 1. 检查分支
        uses: actions/checkout@v2

      - name: 2. 设置 Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: 3. 安装依赖
        run: pnpm install --filter="./docs"

      - name: 4. 构建文档
        run: cd docs && pnpm docs:build && mv ./.vitepress/dist/ ../gh-pages/docs/

      - name: 5. 保存并发布文档
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          publish_dir: ./gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          commit_message: Update docs
